# Generated by Django 3.2 on 2023-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='canvas',
            name='dimensions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='canvas',
            name='material',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='material',
            field=models.TextField(null=True),
        ),
    ]
