# Generated by Django 3.2 on 2023-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20230309_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='sku_code',
            field=models.CharField(max_length=6, verbose_name='SKU Code'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sku',
            field=models.CharField(max_length=40, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='sku_code',
            field=models.CharField(max_length=12, verbose_name='SKU Code'),
        ),
        migrations.AlterField(
            model_name='design',
            name='sku_code',
            field=models.CharField(max_length=12, verbose_name='SKU Code'),
        ),
    ]
