# Generated by Django 3.2 on 2023-06-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20230531_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='banner_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Banner URL'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='friendly_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Friendly Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='full_name',
            field=models.CharField(max_length=240, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='sku_code',
            field=models.CharField(max_length=6, null=True, verbose_name='SKU Code'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='friendly_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Friendly Name'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='sku_code',
            field=models.CharField(max_length=12, null=True, verbose_name='SKU Code'),
        ),
        migrations.AlterField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artist'),
        ),
        migrations.AlterField(
            model_name='design',
            name='friendly_name',
            field=models.CharField(max_length=80, null=True, verbose_name='Friendly Name'),
        ),
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='sku_code',
            field=models.CharField(max_length=12, null=True, verbose_name='SKU Code'),
        ),
    ]
